spring:
  datasource:
    url: jdbc:mysql://192.168.24.44:3306/jxd_group?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.jxd.growup.model
server:
  port: 8087