spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grow?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.jxd.growup.model
server:
  port: 8087



